[env:ControleMotores_ESP32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

upload_port = COM6
monitor_port = COM6

upload_speed = 921600
monitor_speed = 115200

build_flags = -Iinclude
; -D PIO_FRAMEWORK_ARDUINO_LITTLEFS_DISABLED

lib_ldf_mode = deep+
lib_extra_dirs =
	lib
	~/Arduino/libraries